
import type { Chemical } from './experiment';

export const commonChemicals: Chemical[] = [
  {
    id: 'hydrochloric-acid-0-1m',
    name: 'Hydrochloric Acid',
    formula: 'HCl',
    type: 'acid',
    concentration: 0.1,
  },
  {
    id: 'sodium-hydroxide-0-1m',
    name: 'Sodium Hydroxide',
    formula: 'NaOH',
    type: 'base',
    concentration: 0.1,
  },
  {
    id: 'phenolphthalein',
    name: 'Phenolphthalein',
    formula: 'C₂₀H₁₄O₄',
    type: 'indicator',
  },
  {
    id: 'sulfuric-acid-0-1m',
    name: 'Sulfuric Acid',
    formula: 'H₂SO₄',
    type: 'acid',
    concentration: 0.1,
  },
  {
    id: 'potassium-hydroxide-0-1m',
    name: 'Potassium Hydroxide',
    formula: 'KOH',
    type: 'base',
    concentration: 0.1,
  },
  {
    id: 'sodium-chloride',
    name: 'Sodium Chloride',
    formula: 'NaCl',
    type: 'salt',
  },
  {
    id: 'distilled-water',
    name: 'Distilled Water',
    formula: 'H₂O',
    type: 'solvent',
  },
  {
    id: 'methyl-orange',
    name: 'Methyl Orange',
    formula: 'C₁₄H₁₄N₃NaO₃S',
    type: 'indicator',
  },
  {
    id: 'acetic-acid-0-1m',
    name: 'Acetic Acid',
    formula: 'CH₃COOH',
    type: 'acid',
    concentration: 0.1,
  },
  {
    id: 'ammonia-0-1m',
    name: 'Ammonia',
    formula: 'NH₃',
    type: 'base',
    concentration: 0.1,
  },
  {
    id: 'copper-sulfate-0-1m',
    name: 'Copper (II) Sulfate',
    formula: 'CuSO₄',
    type: 'salt',
    concentration: 0.1,
  },
  {
    id: 'potassium-permanganate-0-02m',
    name: 'Potassium Permanganate',
    formula: 'KMnO₄',
    type: 'oxidant',
    concentration: 0.02,
  },
  {
    id: 'nitric-acid-0-1m',
    name: 'Nitric Acid',
    formula: 'HNO₃',
    type: 'acid',
    concentration: 0.1,
  },
  {
    id: 'sodium-carbonate-0-1m',
    name: 'Sodium Carbonate',
    formula: 'Na₂CO₃',
    type: 'base',
    concentration: 0.1,
  },
  {
    id: 'silver-nitrate-0-1m',
    name: 'Silver Nitrate',
    formula: 'AgNO₃',
    type: 'salt',
    concentration: 0.1,
  },
  {
    id: 'ethanol',
    name: 'Ethanol',
    formula: 'C₂H₅OH',
    type: 'solvent',
  },
  {
    id: 'bromothymol-blue',
    name: 'Bromothymol Blue',
    formula: 'C₂₇H₂₈Br₂O₅S',
    type: 'indicator',
  },
];
